GET http://localhost:5031/games

###
GET http://localhost:5031/games/1

###
POST http://localhost:5031/games
Content-Type: application/json

{
  "name": "Street Fighter 6",
  "genreId": 1,
  "price": 30.00,
  "releaseDate": "2023-10-05"
}

###
PUT http://localhost:5031/games/1
Content-Type: application/json

{
  "name": "Silent Hill f",
  "genre": "Horror",
  "price": 50.00,
  "releaseDate": "2025-01-01"
}

###
DELETE http://localhost:5031/games/1
Content-Type: application/json

{
  "name": "Silent Hill f",
  "genre": "Horror",
  "price": 50.00,
  "releaseDate": "2025-01-01"
}